{% set component_name = "launch" %}
{% set repo_name = "gz-" + component_name %}
{% set version = "8.0.1" %}
{% set major_version = version.split('.')[0] %}
{% set name = repo_name + major_version %}
{% set component_version = component_name + major_version %}
{% set cxx_name = "lib" + name %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/gazebosim/{{ repo_name }}/archive/{{ repo_name }}{{ major_version }}_{{ version }}.tar.gz
    sha256: a6a6002cc904abbb9233510fc661b5a599d4eb3908783bc6da56070b30cd69bb
    patches:
      - unvendor_backward.patch

build:
  skip: yes  # [ppc64le]
  skip: true  # [not is_python_min]
  number: 1

outputs:
  - name: {{ cxx_name }}
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
      ignore_run_exports:
        - python
        - python_abi
      ignore_run_exports_from:
        - python
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - ninja
        - cmake
        - pkg-config
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - libgz-cmake4
        - libgz-common6
        - libgz-plugin3
        - libgz-tools2
        - libgz-transport14
        - libgz-msgs11
        - libgz-math8
        - libgz-gui9
        - libgz-sim9
        - backward-cpp
        - tinyxml2
        - qt-main
        - libwebsockets  # [linux]
        - libabseil
        - libprotobuf
        - libsdformat15
        - xorg-libxfixes  # [linux]
        - libgl-devel  # [linux]
        - elfutils  # [linux]
        - python
    test:
      commands:
        - test -f ${PREFIX}/include/gz/{{ component_version }}/gz/{{ component_name }}.hh  # [not win]
        - test -f ${PREFIX}/lib/lib{{ name }}.so  # [linux]
        - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\include\\gz\\{{ component_version }}\\gz\\{{ component_name }}.hh exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\{{ name }}\\{{ name }}-config.cmake exit 1  # [win]

  - name: {{ name }}
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      run:
        - {{ pin_subpackage(cxx_name, exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/include/gz/{{ component_version }}/gz/{{ component_name }}.hh  # [not win]
        - test -f ${PREFIX}/lib/lib{{ name }}.so  # [linux]
        - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\include\\gz\\{{ component_version }}\\gz\\{{ component_name }}.hh exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\{{ name }}\\{{ name }}-config.cmake exit 1  # [win]

about:
  home: https://github.com/gazebosim/{{ repo_name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Run and manage programs and plugins.'

extra:
  feedstock-name: {{ repo_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - Tobias-Fischer
