schema_version: 1

context:
  component_name: launch
  repo_name: ${{ "gz-" + component_name }}
  version: 9.0.0
  major_version: "9"
  name: ${{ repo_name + major_version }}
  component_version: ${{ component_name + major_version }}
  cxx_name: ${{ "lib" + name }}
  is_python_min: ${{ python_version.split('.')[0:2] | join('.') | float >= 3.8 }}

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/gazebosim/${{ repo_name }}/archive/${{ repo_name }}${{ major_version }}_${{ version }}.tar.gz
    sha256: a6a6002cc904abbb9233510fc661b5a599d4eb3908783bc6da56070b30cd69bb
    patches:
      - unvendor_backward.patch
      - 299.patch

build:
  skip:
    - ppc64le
  number: 0

outputs:
  - package:
      name: ${{ cxx_name }}
    build:
      script:
        - if: unix
          then: build_cxx.sh
        - if: win
          then: bld_cxx.bat
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ninja
        - cmake
        - pkg-config
      host:
        - libgz-cmake
        - libgz-common
        - libgz-plugin
        - libgz-tools
        - libgz-transport
        - libgz-msgs
        - libgz-math
        - libgz-gui
        - libgz-sim
        - backward-cpp
        - tinyxml2
        - qt-main
        - if: linux
          then:
            - libwebsockets
            - xorg-libxfixes
            - libgl-devel
            - elfutils
        - libabseil
        - libprotobuf
        - libsdformat
        - python
      run_exports:
        - ${{ pin_subpackage(cxx_name, upper_bound='x') }}
    tests:
      - package_contents:
          include:
            - gz/${{ component_version }}/gz/${{ component_name }}.hh
          lib:
            - gz-${{ component_name }}
      - script:
          - cmake-package-check gz-${{ component_name }} --targets gz-${{ component_name }}::gz-${{ component_name }}
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}

  - package:
      name: ${{ name }}
    requirements:
      run:
        - ${{ pin_subpackage(cxx_name, exact=True) }}
      run_exports:
        - ${{ pin_subpackage(cxx_name, upper_bound='x') }}
    tests:
      - script:
          - cmake-package-check gz-${{ component_name }} --targets gz-${{ component_name }}::gz-${{ component_name }}
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}

about:
  homepage: https://github.com/gazebosim/${{ repo_name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: Run and manage programs and plugins.

extra:
  feedstock-name: ${{ repo_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - Tobias-Fischer
    - j-rivero
